#define STM32_PLLXTPRE			STM32_PLLXTPRE_DIV1
#define STM32_PLLMUL_VALUE		9
#define STM32_HSECLK			8000000

#undef  GPIO_USB_CLEAR_TO_ENABLE
#define GPIO_LED_SET_TO_EMIT		8

#define VAL_GPIO_ODR            0xFFFFE7FF
#define VAL_GPIO_CRL            0x88888888      /*  PA7...PA0 */
#define VAL_GPIO_CRH            0x88811881      /* PA15...PA8 */

#define GPIO_USB_BASE	GPIOA_BASE
#define GPIO_LED_BASE	GPIOA_BASE

#define RCC_APB2ENR_IOP_EN	(RCC_APB2ENR_IOPAEN)
#define RCC_APB2RSTR_IOP_RST	(RCC_APB2RSTR_IOPARST)
